
export const FETCH_FOODS = 'FETCH_FOODS';
export const FETCH_FOOD_DETAILS = 'FETCH_FOOD_DETAILS';

export const GET_FOODS_REQUEST = "GET_FOODS_REQUEST";
export const GET_FOODS_SUCCESS = "GET_FOODS_SUCCESS";
export const GET_FOODS_FAIL = "GET_FOODS_FAIL";

export const GET_FOODS_BY_CATEGORY_REQUEST = "GET_FOODS_BY_CATEGORY_REQUEST";
export const GET_FOODS_BY_CATEGORY_SUCCESS = "GET_FOODS_BY_CATEGORY_SUCCESS";
export const GET_FOODS_BY_CATEGORY_FAIL = "GET_FOODS_BY_CATEGORY_FAIL";

export const GET_FOOD_DETAILS_REQUEST = "GET_FOOD_DETAILS_REQUEST";
export const GET_FOOD_DETAILS_SUCCESS = "GET_FOOD_DETAILS_SUCCESS";
export const GET_FOOD_DETAILS_FAIL = "GET_FOOD_DETAILS_FAIL";
export const GET_FOOD_DETAILS_RESET = "GET_FOOD_DETAILS_RESET";
// CART CONSTANT
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CART_RESET = 'CART_RESET'

// ORDERS CONSTANT 
export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";